### ISSUE TITLE
Implement a method to check when there are no more questions left so the app doesn't crash. 

### ISSUE THREAD

**Issue by neddstarkk** [neddstarkk/quizzler-flutter#2]
Right now there's only three questions that I have hard coded in a list. If that approach is followed then the list will run out of questions which means there will be an error, crashing the app. A method needs to be implemented that will check when the list has ended and will handle the error appropriately

**Comment by VinitaPotter** [comment]
Can I work on this?

**Comment by neddstarkk** [comment]
Sure you can, the code is really easy to understand. Just fork and make a pull request when you're done

**Comment by neddstarkk** [comment]
Issued resolved by @ikp-773. Issue will be closed now
